version: '3.8'

services:
    
  database:
    container_name: postgres_db
    image: postgres:13.6
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER $$POSTGRES_DB"]
        interval: 5s
        timeout: 5s
        retries: 5
    environment:
        POSTGRES_DB: "${DB_DATABASE}"
        POSTGRES_USER: "${DB_USERNAME}"
        POSTGRES_PASSWORD: "${DB_PASSWORD}"
        #POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: unless-stopped

volumes:
    postgres-data:
