version: '3.8'

services:

  laravel:
    container_name: my_laravel
    ports:
      - "${APP_PORT}:8000"
    build:
      context: .
      dockerfile: infra/docker/services/laravel/dockerfile-backend
    healthcheck:
      test: ["CMD-SHELL", "healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes: 
      - my-laravel:/laravel # bind mount
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: my_postgres
    image: postgres:13.6
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      #POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: unless-stopped

  mailhog:
    container_name: my_mailhog
    image: 
      'mailhog/mailhog'
    ports:
      - "${MAILHOG_PORT}:8025"
    restart: on-failure

volumes:
  postgres-data:
  my-laravel: