FROM php:8.1.4-fpm-alpine AS base

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions && sync && install-php-extensions \
  @composer \
  gd \
  imagick \
  opcache \
  pcntl \
  pdo_pgsql \
  pgsql \
  redis \
  zip \
  sockets \
  bcmath

RUN apk update && \
  apk add --no-cache git openssh make

WORKDIR /app

COPY ./laravel/composer.json /app/composer.json
COPY ./laravel/composer.lock /app/composer.lock

RUN composer install --no-dev --no-interaction --no-scripts --no-autoloader --no-progress --no-cache

ADD ./laravel /app
ADD ./infra/docker/services/laravel/backend.sh /app
ADD ./infra/docker/services/laravel/healthcheck.sh /app

# Finish the composer install and generate an autoloader now that the full app is copied in
RUN composer install --no-dev --no-interaction --no-progress --optimize-autoloader --no-cache

ENTRYPOINT ["/bin/sh", "backend.sh"]