FROM php:8.1.4-fpm-alpine AS base

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && sync && install-php-extensions \
  @composer \
  gd \
  imagick \
  opcache \
  pcntl \
  pdo_pgsql \
  pgsql \
  redis \
  zip \
  sockets \
  bcmath

RUN apk update && \
  apk add --no-cache git openssh make

WORKDIR /app